### ISSUE TITLE
Go Server?

### ISSUE THREAD

**Issue by cmullins70** [codybuell/donotdisturb#2]
Do I need to have installed and configured a Go server on my machine to use this?

**Comment by codybuell** [comment]
You will need Go installed on your system, either to compile the Go code or to call a `go run` command on the script.  The light needs to be plugged into a computer running that Go code.

**Comment by cmullins70** [comment]
Thanks - is the Python code an alternative script? Equal replacement? 

Thanks for a badass prolect BTW. We're using at MacroFab to teach new employees how to solder....

**Comment by codybuell** [comment]
The Python code in that server folder is intended to be an alternative to the Go code, though it was never progressed very far.  Awesome to hear!
